# Параметры экспорта ресурсов.
# Корневая папка.
root_folder: ''
# Список папок с исходниками ПЧ.
src_folders:
    - src_folder: ''
    - src_folder: ''
    - src_folder: ''
# Cписок папок с конфигами ЛК.
src_ess_folders:
    - src_ess_folder: ''
    - src_ess_folder: ''
    - src_ess_folder: ''
